spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates: # Pre-conditions to match in order to be able to consume the route.
          - Path=/api-products/**
          #- Method=GET,POST # methods allowed
          #- Header=token, \d+ # must be this token header at least, or an specific Content-Type header in example..
        filters:
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
          - name: ProductFilter
            args:
              message: Cookie filter for api-products on application.yml using a GatewayFilterFactory java
              cookieName: ProductFilter
              cookieValue: CookieValue
      - id: item-service
        uri: lb://item-service
        predicates:
          - Path=/api-items/**
        filters:
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
          - AddRequestHeader=req-token-header, 12345
          - AddResponseHeader=res-token-header, 678910
          - AddRequestParameter=req-parameter, joan