resilience4j:
  circuitbreaker:
    configs: 
      default-config: # We set the name for this config
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4 # number of ok requests to be redimish
    instances:
      vfsBackendCircuitBreaker:  # we set a name to identify it.
        base-config: default-config # name already set before
  timelimiter:
    configs:
      default-config:
        timeout-duration: 5s
    instances:
      vfsBackendCircuitBreaker:
        base-config: default-config

spring:
  cloud:
    gateway:
      routes:
      - id: vfs-backend-service
        uri: lb://vfs-backend-service
        predicates: # Pre-conditions to match in order to be able to consume the route.
          - Path=/api-vfs-ccc-pre/**
          #- Method=GET,POST,PATCH,UPDATE,DELETE # methods allowed
          #- Header=token, \d+ # must be this token header at least, or an specific Content-Type header in example..
        filters:
          - vfsBackendCircuitBreaker #the name we set up before in this document
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...