resilience4j:
  circuitbreaker:
    configs: 
      default-config: # We set the name for this config
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4 # number of ok requests to be redimish
    instances:
      ProductsCircuitBreaker:  # we set a name to identify it.
        base-config: default-config # name already set before
      ItemsCircuitBreaker:  # we set a name to identify it.
        base-config: default-config # name already set before
      UsersCircuitBreaker:  # we set a name to identify it.
        base-config: default-config # name already set before
      OauthCircuitBreaker:  # we set a name to identify it.
        base-config: default-config # name already set before
  timelimiter:
    configs:
      default-config:
        timeout-duration: 5s
    instances:
      ProductsCircuitBreaker:
        base-config: default-config
      ItemsCircuitBreaker:
        base-config: default-config
      UsersCircuitBreaker:
        base-config: default-config
      OauthCircuitBreaker:
        base-config: default-config

spring:
  cloud:
    gateway:
      routes:
      - id: oauth-service
        uri: lb://oauth-service
        predicates: # Pre-conditions to match in order to be able to consume the route.
          - Path=/api-oauth/**
          #- Method=GET,POST # methods allowed
          #- Header=token, \d+ # must be this token header at least, or an specific Content-Type header in example..
        filters:
          - CircuitBreaker=OauthCircuitBreaker #the name we set up before in this document
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
      - id: users-service
        uri: lb://users-service
        predicates: # Pre-conditions to match in order to be able to consume the route.
          - Path=/api-users/**
          #- Method=GET,POST # methods allowed
          #- Header=token, \d+ # must be this token header at least, or an specific Content-Type header in example..
        filters:
          - CircuitBreaker=UsersCircuitBreaker #the name we set up before in this document
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
      - id: product-service
        uri: lb://product-service
        predicates: # Pre-conditions to match in order to be able to consume the route.
          - Path=/api-products/**
          #- Method=GET,POST # methods allowed
          #- Header=token, \d+ # must be this token header at least, or an specific Content-Type header in example..
        filters:
          - CircuitBreaker=ProductsCircuitBreaker #the name we set up before in this document
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
          - name: ProductFilter
            args:
              message: Cookie filter for api-products on application.yml using a GatewayFilterFactory java
              cookieName: ProductFilter
              cookieValue: CookieValue
      - id: item-service
        uri: lb://item-service
        predicates:
          - Path=/api-items/**
        filters:
          - CircuitBreaker=ItemsCircuitBreaker #the name we set up before in this document
          - StripPrefix=1 # number of parts/slides in the path below /1/2/3...
          - AddRequestHeader=req-token-header, 12345
          - AddResponseHeader=res-token-header, 678910
          - AddRequestParameter=req-parameter, joan